config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'events#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/enrollment', to: 'enrollments#create'


  resources :events, only: %i[show new create index]
  resources :users, only: %i[show new create index]
  resources :enrollments, only: [:create, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  validates :date, presence: true
  validates :description, presence: true
  has_many :enrollments
  has_many :attendees, through: :enrollments, source: :user
  scope :past, -> { where('date < ?', Date.today) }
  scope :upcoming, -> { where('date >= ?', Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true, presence: true, length: { in: 4..12 }
  has_many :enrollments
  has_many :events, class_name: 'Event', inverse_of: :creator
  has_many :attended_events, through: :enrollments, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def create
    event = Event.find(params[:event_id])
    if Enrollment.where(event_id: event.id, user_id: params[:user_id]).count.positive?
      flash[:notice] = 'Already Enrolled For this Event!'
      redirect_to event_path(event)
    else
      enrollment = Enrollment.new(event_id: event.id, user_id: params[:user_id])
      if enrollment.save
        flash[:notice] = 'Enrolled Successfully!'
        redirect_to event_path(event)

      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @username = current_user.name if logged_in?
    @events_past = Event.past.all
    @events_upcoming = Event.upcoming.all
  end

  # GET /events/1 or /events/1.json
  def show
    @events_upcoming = Event.upcoming
    @event = Event.find(params[:id])
    @creator = Event.find(params[:id]).creator
  end

  # GET /events/new
  def new
    @event = Event.new
    @username = current_user.name
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :location, :description, :date, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in, only: :new

  def new; end

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      login(user)
      redirect_to root_path
    else
      flash.now[:notice] = 'User does not exist'
      render :new
    end
  end

  def destroy
    @current_user = nil
    session[:id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end

  private

  def logged_in
    redirect_to root_path if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: %i[ create show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
    @events_past = Event.past.all
    @events_upcoming = Event.upcoming.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    # @user = User.new(user_params)

    # respond_to do |format|
    #   if @user.save
    #     format.html { redirect_to @user, notice: "User was successfully created." }
    #     format.json { render :show, status: :created, location: @user }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end

    @user = User.new(user_params)

    if @user.save
      login @user
      # puts @user
      redirect_to @user
    else
      render :new
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    # params.fetch(:user, {})
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def creator(user_id)
    @creator = User.find_by(id: user_id).name
  end

  def attendees_list(event_obj = nil)
    list = ' '
    event_obj ||= @event
    event_obj.attendees.each do |attendee|
      list = "#{list}#{attendee.name}, "
    end
    list
  end

  def enroll_button
    (return unless logged_in? && (@event.date >= Date.today))
    button_to 'Enroll', enrollment_path(event_id: @event.id, user_id: current_user.id), method: :post
  end

  def enroll_upcoming_events(event)
    logged_in? ? (button_to 'Enroll', enrollment_path(event_id: event.id, user_id: current_user.id), method: :post) : ''
  end

  def new_event
    logged_in? ? (link_to 'Host New Event', new_event_path) : (link_to 'Host New Event', login_path)
  end

  def my_events_link
    link_to 'My Events', user_path(@current_user.id) if logged_in?
  end

  def logout_link
    (link_to 'Logout', logout_path) if logged_in?
  end

  def new_user_link
    (link_to 'New User', new_user_path) unless logged_in?
  end

  def login_link
    (link_to 'Login', login_path) unless logged_in?
  end

  def events_all
    link_to 'Back to All Events', root_path
  end

  def username_if_logged
    @username if logged_in?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:id]) if session[:id]
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/enrollments/create.html.erb
<h1>Enrollments#create</h1>
<p>Find me in app/views/enrollments/create.html.erb</p>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "Name" %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date, placeholder: "Date" %>
  <br>
  <%= f.label :location %>
  <%= f.text_field :location, placeholder: "Location" %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description, placeholder: "Description" %>
  <br>
  <hr>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<br>
<nav>
  <%= my_events_link %>&nbsp
  <%= login_link %>&nbsp
  <%= new_user_link %>&nbsp
  <%= new_event %>&nbsp
  <%= logout_link %>&nbsp
  <h3><%= username_if_logged %></h3>
</nav>
<h1>Private Events</h1>
<hr>
<p id="notice"><%= notice %></p>
<hr>
<table>
  <thead>
    <h3><span style="color: red;">Past Events</span></h3>
    <tr>
      <th>Creator</th>
      <th>Event</th>
      <th>Date</th>
      <th>Location</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <% @events_past.sort_by(&:date).each do |event| %>
      <tr>
        <td><%= creator(event.user_id) %></td>
        <td><%= link_to event.name, event %></td>
        <td><%= event.date %></td>
        <td><%= event.location %></td>
        <td><%= event.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<table>
  <h3><span style="color: green;">Upcoming Events</span></h3>
  <thead>
    <tr>
      <th>Creator</th>
      <th>Event</th>
      <th>Date</th>
      <th>Location</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @events_upcoming.sort_by(&:date).each do |event| %>
      <tr>
        <td><%= creator(event.user_id) %></td>
        <td><%= link_to event.name, event %></td>
        <td><%= event.date %></td>
        <td><%= event.location %></td>
        <td><%= event.description %></td>
        <td><%= enroll_upcoming_events(event) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<br>

app/views/events/new.html.erb
<br>
<%= events_all %>
<h1>New <%= @username %>'s Event</h1>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<br>
Would you like to HOST an Event? <%= new_event %>
<br>
<%= events_all %> <br>
<h2>Event name: <%= @event.name %></h2>
<strong>Creator: </strong> <%= @creator.name %> <br>
<strong>Date: </strong> <%= @event.date %> <br>
<strong>Location: </strong><%= @event.location %><br>
<strong>Description: </strong><%= @event.description %>
<br>
<h3>Attendees: </h3>
<%= attendees_list %>
<br>
<br>
<%= enroll_button %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%
=begin%>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
<%
=end%>
    <%
=begin%>
 <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
<%
=end%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "Name"%>
  <br>
  <br>
  <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Users</h1>
<table>
    <thead>
        <tr>
            <th colspan="3">ID</th>
            <th colspan="3">Name</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <br>
        </tr>
        <% end %>
    </tbody>
</table>
<br>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<br>
<%= link_to 'Back to Events', root_path %>
<h1>New User</h1>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<br>
Would you like to HOST an Event? <%= new_event %><br>
<%= events_all %>
<h2><%= @user.name %>'s events</h2>
<hr>
<table>
  <thead>
    <h3>Hosted Events</h3>
    <tr>
      <th>Event ID</th>
      <th>Event</th>
      <th>Date</th>
      <th>Location</th>
      <th>Description</th>
      <th>Attendees</th>
    </tr>
  </thead>
  <tbody>
    <% @user.events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= link_to event.name, event %></td>
        <td><%= event.date %></td>
        <td><%= event.location %></td>
        <td><%= event.description %></td>
        <td><%= attendees_list(event) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr />
<table>
  <thead>
    <h3><span style="color: red;">Past Events</span></h3>
    <tr>
      <th>Event ID</th>
      <th>Event</th>
      <th>Date</th>
      <th>Location</th>
      <th>Description</th>
      <th>Attendees</th>
    </tr>
  </thead>
  <tbody>
    <% @user.attended_events.sort_by(&:date).each do |event| %>
      <% if event.date <= Date.today %>
        <tr>
          <td><%= event.id %></td>
          <td><%= link_to event.name, event %></td>
          <td><%= event.date %></td>
          <td><%= event.location %></td>
          <td><%= event.description %></td>
          <td><%= attendees_list(event) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<table>
  <thead>
    <h3><span style="color: green;">Upcoming Events</span></h3>
    <tr>
      <th>Event ID</th>
      <th>Event</th>
      <th>Date</th>
      <th>Location</th>
      <th>Description</th>
      <th>Attendees</th>
    </tr>
  </thead>
  <tbody>
    <% @user.attended_events.sort_by(&:date).each do |event| %>
      <% if event.date > Date.today %>
        <tr>
          <td><%= event.id %></td>
          <td><%= link_to event.name, event %></td>
          <td><%= event.date %></td>
          <td><%= event.location %></td>
          <td><%= event.description %></td>
          <td><%= attendees_list(event) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<hr>